<html>
  <head>
    <title>
pils - Python Irc Log Stats - examples
    </title>
    <link rel="stylesheet" href="/pils.css" type="text/css" />
  <head>
  <body>
<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
  <tr>
    <td align="center" bgcolor="#eeeeee" colspan="3" valign="middle">
      <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td colspan="3" height="10"><img src="/gfx/pixel.gif" alt="" border="0" height="10" width="1" /></td>
        </tr>
        <tr>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="10" /></td>
          <th align="center">
<a href="/"><img src="/gfx/pils_logo.png" alt="pils - Python Irc Log Stats" border="0" height="200" width="600" /></a>
          </th>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="10" /></td>
        </tr>
        <tr>
          <td colspan="3" height="10"><img src="/gfx/pixel.gif" alt="" border="0" height="10" width="1" /></td>
        </tr>
      </table>
    </th>
    <td bgcolor="#444444" width="1"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="1" /></td>
  </tr>
  <tr>
    <td bgcolor="#eeeeee" height="1"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="1" /></td>
    <td bgcolor="#444444" colspan="3" height="1"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="1" /></td>
  </tr>
  <tr>
    <td align="left" bgcolor="#eeeeee" valign="top" width="150">
      <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td colspan="3" height="10"><img src="/gfx/pixel.gif" alt="" border="0" height="10" width="1" /></td>
        </tr>
        <tr>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1"
width="10" /></td>
          <td align="left" width="15">
          </td>
          <td align="left">
<a href="/index.php">homepage</a>
          </td>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1"
width="10" /></td>
        </tr>
        <tr>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1"
width="10" /></td>
          <td align="left" width="15">
          </td>
          <td align="left">
<a href="/news.php">news</a>
          </td>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1"
width="10" /></td>
        </tr>
        <tr>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1"
width="10" /></td>
          <td align="left" class="selected_menu_item" width="15">
&raquo;
          </td>
          <td align="left">
<a class="selected_menu_item" href="/examples.php">examples</a>

          </td>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1"
width="10" /></td>
        </tr>
        <tr>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1"
width="10" /></td>
          <td align="left" width="15">
          </td>
          <td align="left">
<a href="/faq.php">f.a.q.</a>
          </td>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1"
width="10" /></td>
        </tr>
        <tr>
          <td colspan="3" height="10"><img src="/gfx/pixel.gif" alt="" border="0" height="10" width="1" /></td>
        </tr>
      </table>
    </td>
    <td bgcolor="#444444" rowspan="2" width="1"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="1" /></td>
    <td align="left" bgcolor="#ffffff" rowspan="2" valign="top">
      <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td colspan="3" height="10"><img src="/gfx/pixel.gif" alt="" border="0" height="10" width="1" /></td>
        </tr>
        <tr>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="10" /></td>
          <td align="left">
<p>
  <b>
    statistics generated by pils:
  </b>
  <br />
  <ul>
    <li>
      <a href="http://pils.custom-scripting.de/kahakai.html">http://pils.custom-scripting.de/kahakai.html</a>
    </li>
    <li>
      <a href="http://pils.custom-scripting.de/knacken.html">http://pils.custom-scripting.de/knacken.html</a>
    </li>
  </ul>
  <br />
  I would be glad to add your statistics here - just drop me a
  <a href="http://developer.berlios.de/users/nikl/">note</a>.
</p>
          </td>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="10" /></td>
        </tr>
        <tr>
          <td colspan="3" height="10"><img src="/gfx/pixel.gif" alt="" border="0" height="10" width="1" /></td>
        </tr>
      </table>
    </td>
    <td bgcolor="#ffffff" rowspan="2" width="1"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="1" /></td>
  </tr>
  <tr>
    <td align="center" bgcolor="#eeeeee" valign="bottom" width="150">
      <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td colspan="3" height="10"><img src="/gfx/pixel.gif" alt="" border="0" height="10" width="1" /></td>
        </tr>
        <tr>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="10" /></td>
          <td align="center">
project hosted at
<a href="http://developer.berlios.de/projects/pils/"><img src="http://developer.berlios.de/bslogo.php?group_id=1274" width="124" height="32" border="0" alt="BerliOS Developer Logo" /></a>
          </td>
          <td width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="10" /></td>
        </tr>
        <tr>
          <td colspan="3" height="10"><img src="/gfx/pixel.gif" alt="" border="0" height="10" width="1" /></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td bgcolor="#444444" colspan="2" height="1"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="1" /></td>
    <td bgcolor="#ffffff" colspan="2" height="1"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="1" /></td>
  </tr>
  <tr>
    <td colspan="4" height="10"><img src="/gfx/pixel.gif" alt="" border="0" height="10" width="1" /></td>
  </tr>
  <tr>
    <td align="center" colspan="4">
      <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td height="1" width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="10" /></td>
    <td bgcolor="#cccccc" height="1"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="1" /></td>
          <td height="1" width="10"><img src="/gfx/pixel.gif" alt="" border="0" height="1" width="10" /></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td align="center" colspan="4">
(c) 2003 - 2004 - <a href="http://pils.berlios.de">Nikolaus Schlemm</a> - pils.berlios.de
    </td>
  </tr>
</table>
  </body>
</html>
